// ERP workflow e2e (Tests A–H of the brief + the new modules). Real Next build + PostgREST + Postgres RLS + Chromium. Run via scripts/e2e.sh
import { chromium } from 'playwright-core'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import pg from 'pg'

const BASE = process.env.E2E_BASE
const OUT = 'tests/e2e/shots/erp'; fs.mkdirSync(OUT, { recursive: true })
const results = []
const ok = (cond, msg) => { results.push([!!cond, msg]); console.log(`${cond ? '  ✓' : '  ✗'} ${msg}`) }
const db = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const one = async (sql, args = []) => (await db.query(sql, args)).rows[0]
const exe = fs.readdirSync('/opt/pw-browsers').filter(d => d.startsWith('chromium-')).map(d => `/opt/pw-browsers/${d}/chrome-linux/chrome`).find(p => fs.existsSync(p))
const browser = await chromium.launch({ executablePath: exe })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true }); const p = await ctx.newPage()
p.on('pageerror', e => ok(false, `JS error on ${p.url()}: ${e.message}`)); p.on('dialog', d => d.accept())
const settle = async (ms = 600) => { await p.waitForLoadState('networkidle').catch(() => {}); await p.waitForTimeout(ms) }
const body = () => p.locator('main').innerText()
const dlg = () => p.locator('dialog[open]')
const menu = async item => { await p.getByRole('button', { name: 'More actions' }).click(); await p.getByRole('menuitem', { name: item }).click() }
const shot = n => p.screenshot({ path: `${OUT}/${n}.png`, fullPage: true })
const pdfPages = f => Number(/Pages:\s+(\d+)/.exec(execFileSync('pdfinfo', [f]).toString())?.[1] ?? 0)
const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64')
const docId = () => p.url().split('/').pop().split('?')[0]
const yr = new Date().getFullYear()
const EMAIL = `erp-owner-${Date.now()}@alsaqr.test`   // unique per run, so the suite can be re-run against a held stack
const side = name => p.locator('aside').getByRole('link', { name, exact: true })

try {
  console.log('\n[E0] Setup')
  await p.goto(`${BASE}/signup`); await p.getByLabel('Work email').fill(EMAIL); await p.getByLabel('Password').fill('correct-horse-battery'); await p.getByRole('button', { name: 'Create account' }).click()
  await p.waitForURL('**/onboarding'); await p.getByLabel('Company name').fill('Al Saqr ERP Test'); await p.getByLabel('Your full name').fill('Erp Owner'); await p.getByRole('button', { name: 'Create company' }).click(); await p.waitForURL(`${BASE}/`)
  const co = (await one(`select p.company_id from profiles p join auth.users u on u.id=p.id where u.email=$1`, [EMAIL])).company_id
  ok(await side('Expenses').isVisible() && await side('Products & Services').isVisible() && await side('Audit Log').isVisible() && await side('Trash').isVisible(), 'sidebar: Expenses, Products & Services, Audit Log, Trash are live')

  console.log('\n[A1] Customer with duplicate detection')
  await p.goto(`${BASE}/parties?new=customer`); await settle()
  ok(await dlg().isVisible(), 'Ctrl+K quick action “Add customer” opens the form directly (?new=customer)')
  await dlg().getByLabel('Customer / company name *').fill('ABC Contracting LLC'); await dlg().getByLabel('Phone').fill('+971 50 123 4567'); await dlg().getByLabel('TRN').fill('100123456700003')
  await dlg().getByLabel('Address').fill('Office 12, Al Saqr Building\nMusaffah M-44\nAbu Dhabi'); await dlg().getByLabel('Credit terms (days)').fill('45')
  await dlg().getByRole('button', { name: 'Save' }).click(); await settle(900)
  await p.getByRole('button', { name: 'Add client' }).click()
  await dlg().getByLabel('Customer / company name *').fill('ABC Contracting L.L.C.'); await dlg().getByLabel('Phone').fill('050 123 4567'); await dlg().getByRole('button', { name: 'Save' }).click(); await settle(900)
  ok(/Possible duplicate/.test(await dlg().innerText()) && /similar name|same phone/.test(await dlg().innerText()), 'similar customer → “Possible duplicate” warning (name + phone), not silently blocked')
  ok((await one(`select count(*)::int n from customers where company_id=$1`, [co])).n === 1, 'nothing saved until confirmed')
  await dlg().getByLabel(/This is a different customer/).check(); await dlg().getByRole('button', { name: 'Save' }).click(); await p.locator('dialog[open]').waitFor({ state: 'detached', timeout: 10000 }).catch(() => {}); await settle(600)
  const n2c = (await one(`select count(*)::int n from customers where company_id=$1`, [co])).n
  ok(n2c === 2, `confirmed → second customer saved${n2c === 2 ? '' : ' — ' + (await dlg().innerText().catch(() => '')).slice(-200)}`)
  const cid = (await one(`select id from customers where company_id=$1 and name='ABC Contracting LLC'`, [co])).id

  console.log('\n[A2] Catalog')
  await p.goto(`${BASE}/catalog`); await settle()
  await p.getByRole('button', { name: /starter list/ }).click(); await settle(1000)
  ok((await one(`select count(*)::int n from catalog_items where company_id=$1`, [co])).n === 11, 'starter products & services added (MS Handrail, Staircase, Gate …)')
  await db.query(`update catalog_items set rate=185, description='MS handrail 50mm pipe, primer + 2 coats paint' where company_id=$1 and name='MS Handrail'`, [co])

  console.log('\n[D1] Double-click “New quotation” → one draft')
  await p.goto(`${BASE}/invoices`); await settle()
  const before = (await one(`select count(*)::int n from invoices where company_id=$1`, [co])).n
  await p.getByRole('button', { name: 'New quotation' }).first().dblclick(); await p.waitForURL(/\/invoices\/[0-9a-f-]{36}$/); await settle(1200)
  ok((await one(`select count(*)::int n from invoices where company_id=$1`, [co])).n === before + 1, 'double click created exactly ONE quotation (idempotency token)')
  const qid = docId(), qnum = (await one(`select number from invoices where id=$1`, [qid])).number
  ok(qnum === `AS-002600/${yr}`, `numbered ${qnum}`)

  console.log('\n[A3] Quotation with 10 items, autofill, catalog, discount, VAT categories, autosave')
  await p.locator('button[aria-haspopup="listbox"]').first().click(); await p.getByRole('combobox', { name: 'Search customers' }).fill('ABC Contracting LLC'); await p.getByRole('option', { name: /ABC Contracting LLC/ }).first().click()
  ok(await p.getByLabel('Customer TRN').inputValue() === '100123456700003' && (await p.getByLabel('Address').inputValue()).includes('Musaffah'), 'customer picked → TRN, phone and address filled in')
  await p.getByLabel('Line 1 description').fill('Supply and installation of steel staircase with landing')
  const qtys = p.getByLabel('Qty', { exact: true }), rates = p.getByLabel('Rate (AED)', { exact: true })
  await qtys.nth(0).fill('100'); await rates.nth(0).fill('120.50')
  for (let i = 2; i <= 9; i++) {
    await p.getByRole('button', { name: 'Add line' }).click()
    await p.getByLabel(`Line ${i} description`).fill(`Fabrication item ${i} — MS hollow section 100×50×3 as per shop drawing, primer and two coats paint`)
    await qtys.nth(i - 1).fill(String(i)); await rates.nth(i - 1).fill(String(250 + i * 10.25))
  }
  await p.getByRole('button', { name: /Add from catalog/ }).click(); await p.getByRole('combobox', { name: 'Search catalog' }).fill('handrail'); await p.getByRole('option', { name: /MS Handrail/ }).click()
  ok((await p.getByLabel('Line 10 description').inputValue()).includes('MS handrail 50mm pipe') && await rates.nth(9).inputValue() === '185', '“Add from catalog” inserts name, description and rate (editable)')
  await qtys.nth(9).fill('12.5')
  await p.locator('select:has(option[value="exempt"])').nth(8).selectOption('exempt')
  await p.getByLabel('Line discount %').nth(1).fill('10')
  await p.getByLabel('Discount type').selectOption('percent'); await p.getByLabel('Discount (%)').fill('5')
  await p.getByLabel('Add VAT to this quotation (show VAT and grand total)').check()
  await p.waitForTimeout(5500); await settle(500)
  const auto = await one(`select total::text, subtotal::text, discount::text, vat_amount::text, (select count(*)::int from invoice_items where invoice_id=$1) n, (select vat_category from invoice_items where invoice_id=$1 and position=8) v9 from invoices where id=$1`, [qid])
  ok(auto.n === 10 && auto.v9 === 'exempt', `autosave (no click) stored all 10 lines (${auto.n}) incl. the exempt line`)
  ok(/Saved just now|Saved \d+ seconds ago/.test(await p.getByTestId('save-status').innerText()), `status shows “${await p.getByTestId('save-status').innerText()}”`)
  // expected maths (integer fils): lines, 10 % on line 2, 5 % document discount spread pro rata, VAT only on standard lines
  const lines = [[100, 120.5, 0, 's'], ...Array.from({ length: 8 }, (_, k) => [k + 2, 250 + (k + 2) * 10.25, k === 0 ? 10 : 0, k === 7 ? 'e' : 's']), [12.5, 185, 0, 's']]
  const fils = lines.map(([q, r, d]) => { const g = Math.round(Math.round(q * 1000) * Math.round(r * 100) / 1000); return g - Math.round(g * d / 100) })
  const sub = fils.reduce((a, b) => a + b, 0), disc = Math.round(sub * 5 / 100), std = fils.filter((_, i) => lines[i][3] === 's').reduce((a, b) => a + b, 0)
  const stdNet = std - Math.round(disc * std / sub), vat = Math.round(stdNet * 5 / 100), total = sub - disc + vat
  ok(auto.subtotal === (sub / 100).toFixed(2) && auto.discount === (disc / 100).toFixed(2) && auto.vat_amount === (vat / 100).toFixed(2) && auto.total === (total / 100).toFixed(2),
    `server totals match exact fils maths: subtotal ${auto.subtotal}, discount ${auto.discount}, VAT ${auto.vat_amount}, total ${auto.total}`)
  const shown = await p.getByTestId('totals').innerText()
  ok(shown.includes((total / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })) && !/\d\.\d{3,}/.test(shown), 'editor shows the same grand total, always 2 decimals')
  ok((await p.locator('.sales-paper').innerText()).includes('Exempt') && (await p.locator('.sales-paper').innerText()).includes('Less 10% discount'), 'paper notes the exempt line and the line discount')
  await shot('A3-quotation-10-items')

  console.log('\n[A4] Print + PDF (filename) + send history')
  const pr = await ctx.newPage(); await pr.goto(`${BASE}/print/sales/${qid}`); await pr.waitForLoadState('networkidle')
  ok((await pr.title()) === `AS-002600-${yr}_ABC-Contracting-LLC_Quotation`, `print page title = “Save as PDF” file name (${await pr.title()})`)
  await pr.emulateMedia({ media: 'print' }); await pr.pdf({ path: `${OUT}/A4-quotation.pdf`, preferCSSPageSize: true, printBackground: true }); await pr.close()
  ok(pdfPages(`${OUT}/A4-quotation.pdf`) >= 1, `browser PDF rendered (${pdfPages(`${OUT}/A4-quotation.pdf`)} page(s))`)
  const dl = await ctx.request.get(`${BASE}/api/sales/${qid}/pdf`)
  ok(dl.ok() && /filename="AS-002600-\d{4}_ABC-Contracting-LLC_Quotation\.pdf"/.test(dl.headers()['content-disposition'] ?? ''), `download name: ${dl.headers()['content-disposition']?.match(/filename="([^"]+)"/)?.[1]}`)
  fs.writeFileSync(`${OUT}/A4-download.pdf`, await dl.body())
  const txt = execFileSync('pdftotext', ['-layout', `${OUT}/A4-download.pdf`, '-']).toString()
  ok(txt.includes((total / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })), 'downloaded PDF shows the same grand total as the editor')

  console.log('\n[A5] Sent → follow-ups → revision')
  await menu('Mark as sent'); await settle(1000)
  const fu = await db.query(`select due_date::text d from sales_followups where invoice_id=$1 order by due_date`, [qid])
  ok(fu.rows.length === 2, `sending scheduled ${fu.rows.length} follow-ups (${fu.rows.map(r => r.d).join(', ')})`)
  await p.reload(); await settle()
  await p.getByLabel('Line 1 description').fill('Supply and installation of steel staircase with landing — REVISED to 1.2 m width')
  await p.getByRole('button', { name: 'Save', exact: true }).click(); await settle(1200)
  const rev = await one(`select i.revision, r.changes from invoices i join sales_doc_revisions r on r.invoice_id=i.id where i.id=$1`, [qid])
  ok(rev?.revision === 1 && rev.changes.some(c => /Line 1/.test(c)), `edit after sending → Revision 1 stored (“${rev?.changes?.join('; ')}”)`)
  await p.goto(`${BASE}/invoices/${qid}/revisions/0`); await settle()
  ok((await p.locator('.sales-paper').innerText()).includes('steel staircase with landing') && !(await p.locator('.sales-paper').innerText()).includes('REVISED'), 'previous revision opens read-only with the original text')

  console.log('\n[A6] Partial delivery 60 of 100')
  await p.goto(`${BASE}/invoices/${qid}`); await settle()
  await menu('Create delivery note (choose quantities)…'); await p.waitForTimeout(400)
  const inputs = dlg().getByLabel(/Deliver now:/)
  await inputs.first().fill('60'); for (let i = 1; i < await inputs.count(); i++) await inputs.nth(i).fill('0')
  await dlg().getByRole('button', { name: 'Create delivery note' }).click(); await p.waitForURL(u => !u.href.includes(qid)); await settle()
  const dn = await one(`select i.number, i.quotation_id, (select quantity::text from invoice_items where invoice_id=i.id) q from invoices i where i.id=$1`, [docId()])
  ok(/^DL-\d+$/.test(dn.number) && dn.quotation_id === qid && dn.q === '60.000', `delivery note ${dn.number}: 60 delivered, linked to the quotation`)
  await p.goto(`${BASE}/invoices/${qid}`); await settle()
  const qd = await one(`select ordered::text o, delivered::text d from quotation_delivery where quotation_id=$1 order by ordered desc limit 1`, [qid])
  ok((await body()).includes('Delivered 60 / 100') && qd.o === '100.000' && qd.d === '60.000', 'quotation shows Delivered 60 / 100 (40 remaining for the next delivery)')

  console.log('\n[A7] Convert to invoice (quotation untouched)')
  const qBefore = await one(`select total::text, (select string_agg(description, '|' order by position) from invoice_items where invoice_id=$1) d from invoices where id=$1`, [qid])
  await menu('Convert to invoice'); await p.waitForURL(u => !u.href.includes(qid)); await settle()
  const iid = docId()
  const inv = await one(`select number, status, quotation_id, total::text, terms, (select count(*)::int from invoice_items where invoice_id=$1) n, due_date::text due, issue_date::text iss from invoices where id=$1`, [iid])
  const qAfter = await one(`select status, total::text, (select string_agg(description, '|' order by position) from invoice_items where invoice_id=$1) d from invoices where id=$1`, [qid])
  ok(/^INV-\d+$/.test(inv.number) && inv.quotation_id === qid && inv.n === 10 && inv.total === qBefore.total && inv.terms.length > 0, `invoice ${inv.number}: 10 lines, same total ${inv.total}, terms copied, linked`)
  ok(qAfter.status === 'converted' && qAfter.total === qBefore.total && qAfter.d === qBefore.d, 'quotation content unchanged; status Converted')
  ok(inv.due === new Date(Date.parse(inv.iss + 'T00:00:00Z') + 45 * 864e5).toISOString().slice(0, 10), `due date from the customer’s 45-day credit terms (${inv.due})`)

  console.log('\n[A8] Credit note, payments (double submit), cheque cleared → balance (Test H)')
  await menu('Issue tax invoice'); await settle(1000)
  await menu('Create credit note'); await p.waitForURL(u => !u.href.includes(iid)); await settle()
  const cnId = docId()
  for (let i = 0; i < 9; i++) { await p.getByRole('button', { name: 'Remove line' }).first().click() }
  await p.getByLabel('Line 1 description').fill('Credit: damaged handrail section returned'); await p.getByLabel('Qty', { exact: true }).first().fill('1'); await p.getByLabel('Rate (AED)', { exact: true }).first().fill('1000')
  await p.getByLabel('Line discount %').first().fill('0'); await p.locator('select:has(option[value="exempt"])').first().selectOption('standard')
  await p.getByLabel('Discount type').selectOption('amount'); await p.getByLabel('Discount (AED)').fill('0')
  await p.getByRole('button', { name: 'Save', exact: true }).click(); await settle(1000)
  await menu('Issue credit note'); await settle(1200)
  const cn = await one(`select status, total::text from invoices where id=$1`, [cnId])
  const bal1 = await one(`select balance::text, credited::text from invoice_balances where id=$1`, [iid])
  ok(cn.status === 'sent' && cn.total === '1050.00' && bal1.credited === '1050.00', `credit note issued (AED ${cn.total}) → invoice credited ${bal1.credited}, balance ${bal1.balance}`)
  await p.goto(`${BASE}/invoices/${iid}`); await settle()
  await p.getByRole('button', { name: 'Record payment' }).click()
  await dlg().getByLabel('Amount (AED) *').fill('8000'); await dlg().getByLabel('Reference').fill('TT-ERP-1')
  await dlg().getByRole('button', { name: 'Save payment' }).dblclick(); await settle(1500)
  ok((await one(`select count(*)::int n from payments where invoice_id=$1`, [iid])).n === 1, 'Save payment double-clicked → ONE payment (idempotency key + disabled button)')
  ok((await one(`select status from invoices where id=$1`, [iid])).status === 'partially_paid', 'invoice Partially paid')
  // cheque linked to the invoice; cleared only by explicit confirmation
  await p.goto(`${BASE}/cheques`); await settle()
  await p.getByRole('button', { name: 'Add cheque' }).click()
  await dlg().getByLabel('Customer / supplier *').fill('ABC Contracting LLC'); await dlg().getByLabel('Cheque number *').fill('000777'); await dlg().getByLabel('Bank name *').fill('Emirates NBD')
  await dlg().getByLabel('Amount (AED) *').fill('10000'); await dlg().getByLabel('Cheque date *').fill(`${yr}-01-15`)
  await dlg().getByLabel('Linked tax invoice (incoming)').selectOption(iid)
  await dlg().getByRole('button', { name: 'Save cheque' }).click(); await settle(1000)
  const chq = await one(`select id, invoice_id, status from cheques where company_id=$1 and cheque_no='000777'`, [co])
  ok(chq?.invoice_id === iid && chq.status === 'received', 'cheque saved, linked to the invoice')
  const balBefore = (await one(`select balance::text from invoice_balances where id=$1`, [iid])).balance
  ok(Number(balBefore) > 0 && (await one(`select count(*)::int n from payments where cheque_id=$1`, [chq.id])).n === 0, 'cheque date in the past does NOT reduce the balance by itself')
  const upd = async (status, confirm) => {
    await p.locator('tr', { hasText: '000777' }).getByRole('button', { name: 'Update' }).click()
    await dlg().getByLabel('New status').selectOption(status); if (confirm) await dlg().getByText(/I have verified with my bank/).click()
    await dlg().getByRole('button', { name: 'Update status' }).click(); await settle(1200)
  }
  await upd('deposited'); await upd('cleared', true)
  const bal2 = await one(`select balance::text from invoice_balances where id=$1`, [iid]), cp = await one(`select amount::text from payments where cheque_id=$1`, [chq.id])
  ok(cp?.amount === Math.min(10000, Number(balBefore)).toFixed(2) && Number(bal2.balance) === Math.max(0, Number(balBefore) - 10000), `confirmed Cleared → AED ${cp?.amount} applied; balance ${balBefore} → ${bal2.balance}`)

  console.log('\n[A9] Ledger & statement')
  await p.goto(`${BASE}/parties/${cid}/ledger`); await settle()
  const lt = await body()
  ok(lt.includes(inv.number) && lt.includes('Credit note') && lt.includes('Chq 000777') && lt.includes('TT-ERP-1'), 'ledger: invoice (debit), credit note, transfer and cheque payment (credits) with running balance')
  await shot('A9-ledger')
  const st = await ctx.request.get(`${BASE}/api/statements/${cid}`); fs.writeFileSync(`${OUT}/A9-statement.pdf`, await st.body())
  const stTxt = execFileSync('pdftotext', ['-layout', `${OUT}/A9-statement.pdf`, '-']).toString()
  ok(st.ok() && stTxt.includes('STATEMENT OF ACCOUNT') && stTxt.includes(inv.number) && /Statement_ABC-Contracting-LLC_\d{4}-\d{2}-\d{2}\.pdf/.test(st.headers()['content-disposition'] ?? ''), 'statement PDF download (named Statement_ABC-Contracting-LLC_<date>.pdf)')
  const sp = await ctx.newPage(); await sp.goto(`${BASE}/print/statement/${cid}`); await sp.waitForLoadState('networkidle')
  ok((await sp.locator('.sales-paper').innerText()).includes('STATEMENT OF ACCOUNT'), 'statement print view (A4, same paper engine)'); await sp.close()

  console.log('\n[B] Long 3-page quotation (long address, descriptions, terms)')
  const long = 'Supply, fabrication and installation of mild steel staircase stringers 200×75 channel with 6 mm chequered plate treads, 1.1 m high handrail and balusters at 120 mm centres, including welding, grinding, one coat of zinc-rich primer and two coats of polyurethane paint, transport, scaffolding and site cleaning. '
  const bq = (await one(`insert into invoices(company_id,doc_type,number,status,customer_name,customer_address,vat_rate,terms) values ($1,'quotation','AS-LONG-1','draft',$2,$3,5,$4) returning id`, [co, 'Al Saqr Al Ahmar International General Contracting & Steel Fabrication Company LLC (Branch 2)', 'Office 1204, Al Saqr Business Tower, 12th Floor\nSheikh Zayed Road, Plot 345-678\nAl Barsha Heights (Tecom)\nP.O. Box 123456\nDubai\nUnited Arab Emirates', Array.from({ length: 18 }, (_, i) => `Clause ${i + 1}: ${long}`)])).id
  for (let i = 0; i < 26; i++) await db.query(`insert into invoice_items(company_id,invoice_id,position,description,quantity,unit_price) values ($1,$2,$3,$4,2,1500)`, [co, bq, i, `${i + 1}. ${long}`])
  const lp = await ctx.newPage(); await lp.setViewportSize({ width: 794, height: 1123 }); await lp.emulateMedia({ media: 'print' }); await lp.goto(`${BASE}/print/sales/${bq}`); await lp.waitForLoadState('networkidle')
  const over = await lp.evaluate(() => { const r = document.querySelector('.sales-paper').getBoundingClientRect(); return [...document.querySelectorAll('.sales-paper *')].filter(el => { const b = el.getBoundingClientRect(); return b.width && b.right > r.right + 0.5 }).length })
  await lp.pdf({ path: `${OUT}/B-long.pdf`, preferCSSPageSize: true, printBackground: true }); await lp.close()
  const bt = execFileSync('pdftotext', ['-layout', `${OUT}/B-long.pdf`, '-']).toString()
  ok(pdfPages(`${OUT}/B-long.pdf`) >= 3 && over === 0, `long quotation prints on ${pdfPages(`${OUT}/B-long.pdf`)} A4 pages, nothing outside the page (${over})`)
  ok(new Set(bt.match(/\b(\d{1,2})\. Supply, fabrication/g) ?? []).size === 26 && bt.includes('Clause 18'), 'all 26 lines and all 18 clauses present (nothing lost at page breaks)')
  try { execFileSync('pdftoppm', ['-png', '-r', '45', `${OUT}/B-long.pdf`, `${OUT}/B-long`]) } catch {}

  console.log('\n[C] Two users / sessions create quotations at the same moment')
  const c2 = await browser.newContext({ storageState: await ctx.storageState() }), p2 = await c2.newPage(), p3 = await ctx.newPage()
  await Promise.all([p2.goto(`${BASE}/invoices`), p3.goto(`${BASE}/invoices`)]); await Promise.all([p2.waitForLoadState('networkidle'), p3.waitForLoadState('networkidle')])
  await Promise.all([p2.getByRole('button', { name: 'New quotation' }).first().click(), p3.getByRole('button', { name: 'New quotation' }).first().click()])
  await Promise.all([p2.waitForURL(/\/invoices\/[0-9a-f-]{36}$/), p3.waitForURL(/\/invoices\/[0-9a-f-]{36}$/)])
  const [n2, n3] = await Promise.all([p2, p3].map(async x => (await one(`select number from invoices where id=$1`, [x.url().split('/').pop()])).number))
  ok(n2 !== n3 && /^AS-\d{6}\/\d{4}$/.test(n2) && /^AS-\d{6}\/\d{4}$/.test(n3), `simultaneous creation → distinct numbers ${n2} and ${n3}`)
  ok((await one(`select count(*)::int n from (select number from invoices where company_id=$1 and doc_type='quotation' group by number having count(*)>1) x`, [co])).n === 0, 'no duplicate quotation numbers in the database')
  await c2.close(); await p3.close()

  console.log('\n[E] Mobile quotation creation (390 px)')
  const m = await browser.newContext({ viewport: { width: 390, height: 844 }, storageState: await ctx.storageState(), isMobile: true, hasTouch: true }), mp = await m.newPage()
  await mp.goto(`${BASE}/invoices`); await mp.waitForLoadState('networkidle')
  await mp.getByRole('button', { name: 'New quotation' }).first().click(); await mp.waitForURL(/\/invoices\/[0-9a-f-]{36}$/); await mp.waitForLoadState('networkidle')
  await mp.getByLabel('Customer / company name').fill('Mobile Walk-in Customer'); await mp.getByLabel('Line 1 description').fill('Gate repair on site'); await mp.getByLabel('Rate (AED)', { exact: true }).first().fill('750')
  await mp.getByRole('button', { name: 'Save', exact: true }).click(); await mp.waitForTimeout(1500)
  const mid = mp.url().split('/').pop(), mrow = await one(`select customer_name, total::text from invoices where id=$1`, [mid])
  const sw = await mp.evaluate(() => document.documentElement.scrollWidth)
  ok(mrow.customer_name === 'Mobile Walk-in Customer' && Number(mrow.total) === 750 && sw <= 392, `phone: quotation created and saved (AED ${mrow.total}), no horizontal scroll (${sw}px)`)
  await mp.getByRole('tab', { name: 'preview' }).click(); await mp.waitForTimeout(400); await mp.screenshot({ path: `${OUT}/E-mobile-preview.png` })
  ok((await mp.evaluate(() => document.documentElement.scrollWidth)) <= 392, 'phone: A4 preview fits the screen')
  await m.close()

  console.log('\n[F] Dark mode → print stays white')
  const dk = await browser.newContext({ viewport: { width: 1280, height: 900 }, storageState: await ctx.storageState(), colorScheme: 'dark' }), dp = await dk.newPage()
  await dp.addInitScript(() => { try { localStorage.setItem('sf-theme', 'dark') } catch {} })
  await dp.goto(`${BASE}/`); await dp.waitForLoadState('networkidle')
  const darkBg = await dp.evaluate(() => getComputedStyle(document.body).backgroundColor)
  await dp.goto(`${BASE}/print/sales/${qid}`); await dp.waitForLoadState('networkidle'); await dp.emulateMedia({ media: 'print', colorScheme: 'dark' })
  const pc = await dp.evaluate(() => { const s = getComputedStyle(document.querySelector('.sales-paper')); return { bg: s.backgroundColor, fg: s.color, html: getComputedStyle(document.documentElement).backgroundColor, dark: document.documentElement.classList.contains('dark') } })
  await dp.pdf({ path: `${OUT}/F-dark-print.pdf`, preferCSSPageSize: true, printBackground: true }); try { execFileSync('pdftoppm', ['-png', '-r', '40', '-f', '1', '-l', '1', `${OUT}/F-dark-print.pdf`, `${OUT}/F-dark-print`]) } catch {}
  ok(pc.dark && darkBg !== 'rgb(255, 255, 255)' && pc.bg === 'rgb(255, 255, 255)' && pc.fg === 'rgb(17, 17, 17)', `dark UI (${darkBg}) → printed paper white with dark ink (${pc.bg} / ${pc.fg})`)
  await dk.close()

  console.log('\n[G] Approval workflow (optional setting)')
  await db.query(`insert into app_settings(company_id,key,value) values ($1,'sales.require_approval','true') on conflict (company_id,key) do update set value='true'`, [co])
  await p.goto(`${BASE}/invoices/${mid}`); await settle()
  await menu('Mark as sent'); await settle(900)
  ok((await one(`select status from invoices where id=$1`, [mid])).status === 'draft', 'approval required → cannot be sent before approval')
  await menu('Request approval'); await settle(900)
  await p.reload(); await settle()
  await p.getByLabel('Decision *').selectOption('approved'); await p.getByRole('button', { name: 'Save decision' }).click(); await settle(900)
  await menu('Mark as sent'); await settle(900)
  const ap = await one(`select status, approval_status from invoices where id=$1`, [mid])
  ok(ap.approval_status === 'approved' && ap.status === 'sent', 'manager approved → quotation sent')
  await db.query(`update app_settings set value='false' where company_id=$1 and key='sales.require_approval'`, [co])

  console.log('\n[T] Trash & restore, audit log, search, import/export')
  await p.goto(`${BASE}/parties/${(await one(`select id from customers where company_id=$1 and name='ABC Contracting L.L.C.'`, [co])).id}`); await settle()
  await p.getByRole('button', { name: 'Delete' }).click(); await p.waitForURL('**/parties'); await settle()
  ok(!(await body()).includes('ABC Contracting L.L.C.'), 'deleted customer disappears from the list')
  await p.goto(`${BASE}/trash`); await settle()
  ok((await body()).includes('ABC Contracting L.L.C.'), 'it is in Trash')
  await p.locator('tr', { hasText: 'ABC Contracting L.L.C.' }).getByRole('button', { name: 'Restore' }).click(); await settle(900)
  ok((await one(`select deleted_at from customers where company_id=$1 and name='ABC Contracting L.L.C.'`, [co])).deleted_at === null, 'restored')
  await p.goto(`${BASE}/audit`); await settle()
  const at = await body()
  ok(at.includes('Moved to trash') && at.includes('Restored') && at.includes('Erp Owner') && at.includes('Payment'), 'audit log: trash, restore, payment — with the user name')
  await p.goto(`${BASE}/search?q=${encodeURIComponent(qnum)}`); await settle()
  ok((await body()).includes(qnum) && (await body()).includes('ABC Contracting LLC'), `global search finds ${qnum}`)
  await p.goto(`${BASE}/parties`); await settle()
  await p.getByRole('button', { name: 'Import CSV' }).click()
  await dlg().locator('input[type=file]').setInputFiles({ name: 'customers.csv', mimeType: 'text/csv', buffer: Buffer.from('name,phone,email,trn\nNew Gulf Steel LLC,+971 4 555 1234,info@ngs.ae,\nABC Contracting LLC,,,\nBad Row,,not-an-email,\n') })
  await dlg().getByRole('button', { name: 'Import', exact: true }).click(); await settle(1200)
  ok((await one(`select count(*)::int n from customers where company_id=$1 and name='New Gulf Steel LLC'`, [co])).n === 1 && (await one(`select count(*)::int n from customers where company_id=$1 and name='Bad Row'`, [co])).n === 0, 'CSV import: new row added, existing skipped, invalid row rejected')
  const xl = await ctx.request.get(`${BASE}/api/export/customers?format=xlsx`), xb = await xl.body()
  ok(xl.ok() && xb.subarray(0, 2).toString() === 'PK' && /\.xlsx"/.test(xl.headers()['content-disposition']), `Excel export (${xb.length} bytes)`)

  console.log('\n[X] Expenses, project profitability, vehicle maintenance, dashboard')
  await p.goto(`${BASE}/expenses?new=expense`); await settle()
  await dlg().getByLabel('Description *').fill('MS hollow section 100×50×3 — 40 pcs'); await dlg().getByLabel('Amount excl. VAT (AED) *').fill('3200'); await dlg().getByLabel(/^VAT \(AED\)/).fill('160')
  await dlg().getByRole('button', { name: 'Save expense' }).dblclick(); await settle(1200)
  ok((await one(`select count(*)::int n from project_expenses where company_id=$1`, [co])).n === 1, 'expense saved once (double click safe)')
  const scan = await ctx.request.post(`${BASE}/api/expenses/scan`, { multipart: { file: { name: 'r.png', mimeType: 'image/png', buffer: PNG } } })
  const sj = await scan.json().catch(() => ({}))
  ok([200, 422].includes(scan.status()) && (sj.fields || sj.error) && (await one(`select count(*)::int n from project_expenses where company_id=$1`, [co])).n === 1, `receipt OCR endpoint answers safely (${scan.status()}${sj.error ? ': ' + sj.error.slice(0, 60) : ''}) — suggestions only, nothing saved`)
  const veh = (await one(`insert into assets(company_id,kind,name,plate_or_serial) values ($1,'vehicle','Nissan Navara','DXB 12345') returning id`, [co])).id
  await p.goto(`${BASE}/assets/${veh}?tab=maintenance`); await settle()
  await p.getByRole('button', { name: 'Add record' }).click(); await dlg().getByLabel('Work done *').fill('Oil + filter change'); await dlg().getByLabel('Cost (AED)').fill('350'); await dlg().getByLabel('Next due').fill(`${yr + 1}-03-01`)
  await dlg().getByRole('button', { name: 'Save record' }).click(); await settle(1000)
  const vs = await one(`select next_service_date::text n, last_service_date::text l from assets where id=$1`, [veh])
  ok(vs.n === `${yr + 1}-03-01` && vs.l !== null && (await body()).includes('Oil + filter change'), `maintenance recorded → next service ${vs.n} (feeds reminders)`)
  await p.goto(`${BASE}/`); await settle()
  const dt = await body()
  ok(['Outstanding receivables', 'Sales this month', 'Recorded expenses this month', 'Estimated margin', 'Quotation follow-ups due', 'Projects in progress'].every(s => dt.includes(s)), 'dashboard: receivables, monthly sales / expenses / margin, follow-ups, active projects')
  await shot('X-dashboard')
} catch (e) { ok(false, `aborted: ${e.stack || e}`); await p.screenshot({ path: `${OUT}/abort.png`, fullPage: true }).catch(() => {}) }
await browser.close(); await db.end()
const failed = results.filter(r => !r[0]).length
console.log(`\nERP workflow e2e: ${results.length - failed}/${results.length} passed`)
process.exit(failed ? 1 : 0)
