// End-to-end: quotation → invoice → payments → vault, projects, customer profile, OCR of a photo, UX shell. Run via scripts/e2e.sh
import { chromium } from 'playwright-core'
import fs from 'node:fs'
import pg from 'pg'

const BASE = process.env.E2E_BASE
const results = []
const ok = (cond, msg) => { results.push([!!cond, msg]); console.log(`${cond ? '  ✓' : '  ✗'} ${msg}`) }
const db = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const one = async (sql, args = []) => (await db.query(sql, args)).rows[0]
const exe = fs.readdirSync('/opt/pw-browsers').filter(d => d.startsWith('chromium-')).map(d => `/opt/pw-browsers/${d}/chrome-linux/chrome`).find(p => fs.existsSync(p))
const browser = await chromium.launch({ executablePath: exe })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true }); const p = await ctx.newPage()
p.on('pageerror', e => ok(false, `JS error on ${p.url()}: ${e.message}`)); p.on('dialog', d => d.accept())
const settle = async (ms = 700) => { await p.waitForLoadState('networkidle').catch(() => {}); await p.waitForTimeout(ms) }
const body = () => p.locator('body').innerText()
const dlg = () => p.locator('dialog[open]')
const shot = n => p.screenshot({ path: `tests/e2e/shots/${n}.png`, fullPage: true })
const menu = async item => { await p.getByRole('button', { name: 'More actions' }).click(); await p.getByRole('menuitem', { name: item }).click() }
const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64')

try {
  console.log('\n[S1] Login page & shell')
  await p.goto(`${BASE}/login`); await settle()
  ok((await body()).includes('Run the workshop, the paperwork and the payments'), 'login: split layout with product hero')
  await p.waitForSelector('section[aria-label="About SaqrFlow"] canvas', { timeout: 8000 }).catch(() => {}); await p.waitForTimeout(1500)
  ok(await p.locator('section[aria-label="About SaqrFlow"] canvas').count() === 1, 'login: 3D steel hero rendered (WebGL, lazy-loaded)'); await shot('29-login-3d')
  const m0 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const mp0 = await m0.newPage(); await mp0.goto(`${BASE}/login`); await mp0.waitForTimeout(1500)
  ok(await mp0.locator('canvas').count() === 0 && await mp0.getByRole('button', { name: 'Sign in' }).isVisible(), 'login on a phone: no 3D (battery), form first'); await m0.close()
  await p.goto(`${BASE}/signup`); await p.getByLabel('Work email').fill('sales-owner@alsaqr.test'); await p.getByLabel('Password').fill('correct-horse-battery'); await p.getByRole('button', { name: 'Create account' }).click()
  await p.waitForURL('**/onboarding'); await p.getByLabel('Company name').fill('Al Saqr Al Ahmar Welding'); await p.getByLabel('Your full name').fill('Sales Owner'); await p.getByRole('button', { name: 'Create company' }).click(); await p.waitForURL(`${BASE}/`)
  const co = (await one(`select p.company_id from profiles p join auth.users u on u.id=p.id where u.email='sales-owner@alsaqr.test'`)).company_id
  ok(await p.getByRole('link', { name: 'Sales & Invoices' }).isVisible() && !(await p.getByRole('link', { name: /Projects/ }).innerText()).includes('Soon'), 'sidebar: Sales & Invoices and Projects are live (no “Soon”)')
  ok((await body()).includes('FINANCE & PROJECTS') || (await body()).includes('Finance & projects'), 'sidebar is grouped into sections')
  await p.keyboard.press('Control+k'); await p.waitForTimeout(300)
  ok(await p.getByRole('combobox', { name: 'Command' }).isVisible(), 'Ctrl+K opens the command palette')
  await p.keyboard.type('projects'); await p.keyboard.press('Enter'); await p.waitForURL('**/projects')
  ok(true, 'palette navigates to Projects')

  console.log('\n[S2] Branding in Settings')
  await p.goto(`${BASE}/settings`); await settle()
  for (const [kind, label] of [['header', 'Letterhead (quotation & delivery note) image'], ['stamp', 'Company stamp image']]) {
    const f = p.getByLabel(label); await f.setInputFiles({ name: `${kind}.png`, mimeType: 'image/png', buffer: PNG })
    await f.locator('xpath=ancestor::form').getByRole('button', { name: 'Upload' }).click(); await settle(900)
  }
  const brand = (await db.query(`select key, value from app_settings where company_id=$1 and key like 'branding.%'`, [co])).rows
  ok(brand.some(r => r.key === 'branding.header' && String(r.value).startsWith(co + '/branding/')) && brand.some(r => r.key === 'branding.stamp'), 'letterhead + stamp stored in the private company folder')
  await p.getByLabel('Bank details on invoices').fill('Al Saqr Al Ahmar Welding\nADCB · IBAN AE00 0000 0000 0000 0000 000'); await p.getByLabel('Company TRN').fill('100123456700003')
  await p.getByRole('button', { name: 'Save document settings' }).click(); await settle()
  ok((await one(`select value from app_settings where company_id=$1 and key='branding.company_trn'`, [co]))?.value === '100123456700003', 'document defaults saved')
  const anon = await browser.newContext()
  ok((await anon.request.get(`${BASE}/api/branding/stamp`, { maxRedirects: 0 })).status() !== 200, 'stamp image is not public (logged-out request refused)')
  ok((await ctx.request.get(`${BASE}/api/branding/stamp`)).headers()['content-type'] === 'image/png', 'signed-in staff can load the stamp')

  console.log('\n[S3] Quotation builder with live preview')
  await p.goto(`${BASE}/invoices`); await settle()
  ok((await body()).includes('No quotations yet'), 'empty state for quotations')
  await p.getByRole('button', { name: 'New quotation' }).first().click(); await p.waitForURL(/\/invoices\/[0-9a-f-]{36}$/); await settle()
  const qid = p.url().split('/').pop()
  const qnum = (await one(`select number from invoices where id=$1`, [qid])).number
  ok(/^QTN-\d{4}-0001$/.test(qnum), `quotation numbered automatically (${qnum})`)
  await p.getByLabel('Company name').fill('ABC Contracting LLC'); await p.getByLabel('Attention (contact name)').fill('Mr. Ahmed')
  await p.getByText('Save “ABC Contracting LLC” as a customer').click()
  await p.getByLabel('Address').fill('Musaffah M-44, Abu Dhabi'); await p.getByLabel('Working place / site').fill('Villa 22, Fujairah')
  await p.getByLabel('Line 1 description').fill('Supply and installation of steel staircase with handrail')
  await p.getByLabel('Rate (AED)').fill('25000')
  await p.getByRole('button', { name: 'Add line' }).click()
  await p.getByLabel('Line 2 description').fill('Fabrication of steel canopy frame')
  await p.getByLabel('Qty').nth(1).fill('42.5'); await p.getByLabel('Unit').nth(1).selectOption('Sq.Mtr'); await p.getByLabel('Rate (AED)').nth(1).fill('180')
  const paper = p.locator('.sales-paper')
  ok((await paper.innerText()).includes('Fabrication of steel canopy frame') && (await paper.innerText()).includes('32,650.00'), 'live A4 preview updates as you type (total 32,650.00)')
  ok((await body()).includes('Unsaved changes'), 'unsaved-changes indicator')
  await p.keyboard.press('Control+s'); await settle(1200)
  const q = await one(`select total::text, subtotal::text, customer_id, (select count(*)::int from invoice_items where invoice_id=$1) n from invoices where id=$1`, [qid])
  ok(q.total === '32650.00' && q.n === 2 && q.customer_id, `Ctrl+S saves; server recomputed totals (${q.total}), 2 lines, customer created`)
  ok((await body()).includes('All changes saved'), 'saved state shown')
  await shot('30-quotation-builder')
  const pdf = await ctx.request.get(`${BASE}/api/sales/${qid}/pdf`)
  const pdfBuf = await pdf.body()
  ok(pdf.headers()['content-type'] === 'application/pdf' && pdfBuf.subarray(0, 5).toString() === '%PDF-' && pdfBuf.length > 2000, `PDF download (${pdfBuf.length} bytes)`)
  ok((await anon.request.get(`${BASE}/api/sales/${qid}/pdf`, { maxRedirects: 0 })).status() !== 200, 'PDF not downloadable when logged out')
  const pr = await ctx.newPage(); await pr.goto(`${BASE}/print/sales/${qid}`); await pr.waitForLoadState('networkidle')
  ok((await pr.locator('.sales-paper').innerText()).includes(qnum), 'print view renders the A4 paper'); await pr.close()

  console.log('\n[S4] Convert → issue → partial payment → paid')
  await menu('Create Tax Invoice'); await p.waitForURL(u => !u.href.endsWith(qid)); await settle()
  const iid = p.url().split('/').pop()
  const inv = await one(`select number, status, total::text, vat_amount::text, quotation_id from invoices where id=$1`, [iid])
  ok(/^INV-/.test(inv.number) && inv.quotation_id === qid && inv.total === '34282.50' && inv.vat_amount === '1632.50', `invoice created from quotation with 5% VAT (${inv.total})`)
  ok((await one(`select status from invoices where id=$1`, [qid])).status === 'accepted', 'quotation marked accepted')
  await menu('Issue invoice (mark as sent)'); await settle(1000)
  ok((await one(`select status from invoices where id=$1`, [iid])).status === 'sent', 'invoice issued')
  await p.reload(); await settle()
  await p.getByRole('button', { name: 'Record payment' }).click()
  await dlg().getByLabel('Amount (AED) *').fill('20000'); await dlg().getByLabel('Reference').fill('TT-7781'); await dlg().getByRole('button', { name: 'Save payment' }).click(); await settle(1200)
  ok((await one(`select status from invoices where id=$1`, [iid])).status === 'partially_paid', 'partial payment → Partially paid')
  ok((await body()).includes('Balance AED 14,282.50'), 'balance shown on the invoice page')
  await p.getByRole('button', { name: 'Record payment' }).click()
  await dlg().getByLabel('Amount (AED) *').evaluate(e => e.removeAttribute('max'))
  await dlg().getByLabel('Amount (AED) *').fill('99999'); await dlg().getByRole('button', { name: 'Save payment' }).click(); await settle(1000)
  ok(/exceeds the invoice balance/i.test(await dlg().innerText()), 'overpayment rejected by the database with a clear message')
  await dlg().getByLabel('Amount (AED) *').fill('14282.50'); await dlg().getByRole('button', { name: 'Save payment' }).click(); await settle(1200)
  ok((await one(`select status from invoices where id=$1`, [iid])).status === 'paid', 'second payment → Paid')
  await p.reload(); await settle()
  ok((await body()).includes('This invoice has payments, so its lines are locked'), 'paid invoice is locked against edits')
  await menu('Save PDF to Document Vault'); await settle(1500)
  const vd = await one(`select d.id, d.folder, (select count(*)::int from document_versions v where v.document_id=d.id) v, (select count(*)::int from document_relationships r where r.document_id=d.id) r from invoices i join documents d on d.id=i.pdf_document_id where i.id=$1`, [iid])
  ok(vd && vd.folder === 'Customers/ABC Contracting LLC/Invoices' && vd.v === 1 && vd.r === 2, 'invoice PDF archived to Vault → Customers/ABC Contracting LLC/Invoices, linked to invoice + customer')
  await menu('Create Delivery Note'); await p.waitForURL(u => !u.href.endsWith(iid)); await settle()
  const dn = await one(`select number, total::text, source_invoice_id from invoices where id=$1`, [p.url().split('/').pop()])
  ok(/^DN-/.test(dn.number) && dn.total === '0.00' && dn.source_invoice_id === iid, 'delivery note created from the invoice (unpriced)')
  ok((await p.locator('.sales-paper').innerText()).includes('Received By'), 'delivery note preview has Delivered/Received by lines')

  console.log('\n[S5] Hub, receivables, customer profile')
  await p.goto(`${BASE}/invoices?tab=invoice`); await settle()
  ok((await body()).includes(inv.number) && (await body()).includes('Paid'), 'invoice listed with status')
  await p.goto(`${BASE}/invoices?tab=payments`); await settle()
  ok((await body()).includes('TT-7781') && (await body()).includes('20,000.00'), 'payments tab lists both payments')
  const cid = (await one(`select id from customers where company_id=$1 and name='ABC Contracting LLC'`, [co])).id
  await p.goto(`${BASE}/parties/${cid}`); await settle()
  ok((await body()).includes(qnum) && (await body()).includes(inv.number) && (await body()).includes('Received (all time)'), 'customer profile: documents and money received')
  await shot('31-customer-profile')

  console.log('\n[S6] Projects')
  await p.goto(`${BASE}/projects`); await p.getByRole('button', { name: 'New project' }).click()
  await dlg().getByLabel('Project name *').fill('Villa 22 staircase & canopy'); await dlg().getByLabel('Client').selectOption(cid)
  await dlg().getByLabel('Contract value (AED)').fill('100000'); await dlg().getByLabel('Status').selectOption('active')
  await dlg().getByRole('button', { name: 'Create project' }).click(); await p.waitForURL(/\/projects\/[0-9a-f-]{36}$/); await settle()
  const pid = p.url().split('/').pop()
  await p.getByRole('button', { name: 'Add' }).first().click(); await dlg().getByLabel('Milestone *').fill('Delivery to site'); await dlg().getByRole('button', { name: 'Add milestone' }).click(); await settle(900)
  await p.getByRole('button', { name: 'Add' }).nth(1).click(); await dlg().getByLabel('Description *').fill('MS hollow section 100×50×3'); await dlg().getByLabel('Amount (AED) *').fill('12000'); await dlg().getByRole('button', { name: 'Add cost' }).click(); await settle(900)
  await p.getByLabel('Fabrication %').fill('60'); await p.getByRole('button', { name: 'Update progress' }).click(); await settle(900)
  await p.getByRole('button', { name: 'Upload' }).click(); await dlg().locator('input[type=file]').setInputFiles({ name: 'shop-drawing.pdf', mimeType: 'application/pdf', buffer: pdfBuf }); await dlg().getByRole('button', { name: 'Upload' }).click(); await settle(1500)
  await p.reload(); await settle()
  const t = await body()
  ok(t.includes('Delivery to site') && t.includes('MS hollow section') && t.includes('60%') && t.includes('shop-drawing'), 'milestone, cost, progress and drawing on the project page')
  ok(t.includes('88%') || t.includes('88.0%'), 'estimated margin computed (100,000 contract − 12,000 costs)')
  ok((await one(`select count(*)::int n from reminder_sources where company_id=$1 and source_type='milestone'`, [co])).n === 1, 'milestone feeds Smart Reminders')
  await shot('32-project')
  await p.goto(`${BASE}/`); await settle()
  ok((await body()).includes('Sales & receivables') && (await body()).includes('Villa 22 staircase'), 'dashboard: receivables + active projects')

  console.log('\n[S7] Local OCR of a photographed Emirates ID (AI off)')
  const ayub = (await one(`insert into employees(company_id,employee_no,full_name) values ($1,'S-201','Mohammed Ayub') returning id`, [co])).id
  await db.query(`insert into app_settings(company_id,key,value) values ($1,'ai.provider','"rules"'),($1,'ocr.provider','"tesseract"')`, [co])
  await p.goto(`${BASE}/inbox`); await p.getByRole('button', { name: 'Upload documents' }).click()
  await dlg().locator('input[type=file]').setInputFiles({ name: 'eid-photo.png', mimeType: 'image/png', buffer: fs.readFileSync('tests/fixtures/emirates-id-photo.png') })
  await dlg().getByRole('button', { name: 'Upload & analyse' }).click(); await p.waitForURL(/\/inbox\?batch=/, { timeout: 90000 }); await settle()
  const ocr = await one(`select i.status, i.doc_type, i.suggestion, x.fields, x.engine_version from document_inbox i join document_extractions x on x.inbox_id=i.id where i.company_id=$1 and i.file_name='eid-photo.png'`, [co])
  ok(ocr?.doc_type === 'emirates_id' && ocr.engine_version.includes('tesseract'), `photo read on the server (engine ${ocr?.engine_version})`)
  ok(ocr?.fields?.document_number?.value === '784-1990-1234567-6' && ocr.fields.expiry_date?.value === '2027-01-09', 'ID number (check digit verified) and expiry extracted from the image')
  ok(ocr?.suggestion?.owner?.id === ayub, 'matched to employee Mohammed Ayub')

  console.log('\n[S8] Mobile')
  const m = await browser.newContext({ viewport: { width: 390, height: 844 }, storageState: await ctx.storageState() }); const mp = await m.newPage()
  await mp.goto(`${BASE}/invoices/${qid}`); await mp.waitForLoadState('networkidle')
  ok(await mp.getByRole('tab', { name: 'preview' }).isVisible(), 'mobile: edit / preview toggle')
  await mp.getByRole('tab', { name: 'preview' }).click(); await mp.waitForTimeout(400)
  const sw = await mp.evaluate(() => document.documentElement.scrollWidth)
  ok(sw <= 392, `mobile: A4 preview scales to fit, no horizontal scroll (${sw}px)`)
  await mp.screenshot({ path: 'tests/e2e/shots/33-mobile-preview.png' })
} catch (e) { ok(false, `aborted: ${e.stack || e}`) }
finally {
  await browser.close(); await db.end()
  const failed = results.filter(r => !r[0]).length
  console.log(`\nSales/projects e2e: ${results.length - failed}/${results.length} passed`)
  process.exit(failed ? 1 : 0)
}
