// Shell-level localisation scaffold. English is complete; Arabic (RTL) and Bengali cover navigation and chrome only.
export const LOCALES = ['en', 'ar', 'bn'] as const
export type Locale = (typeof LOCALES)[number]
export const isRtl = (l: string) => l === 'ar'
export const LOCALE_NAMES: Record<Locale, string> = { en: 'English', ar: 'العربية', bn: 'বাংলা' }

type Key = 'inbox' | 'overview' | 'documents' | 'employees' | 'vault' | 'cheques' | 'invoices' | 'projects' | 'parties' | 'assets' | 'reminders' | 'calendar' | 'reports' | 'assistant' | 'users' | 'settings' | 'search' | 'signout' | 'expenses' | 'catalog' | 'audit' | 'trash' | 'leads' | 'site_visits' | 'work_orders' | 'tasks' | 'site_reports' | 'approvals' | 'brief'
const dict: Record<Locale, Record<Key, string>> = {
  en: { inbox: 'Smart Inbox', overview: 'Dashboard', documents: 'Company Documents', employees: 'Employees & Labour', vault: 'Document Vault', cheques: 'Banking & Cheques', invoices: 'Sales & Invoices', projects: 'Projects', parties: 'Customers & Suppliers', assets: 'Vehicles & Assets', reminders: 'Reminders', calendar: 'Calendar', reports: 'Reports & Analytics', assistant: 'Averiqo AI', users: 'User Management', settings: 'Settings', search: 'Search customers, quotations, invoices, people, vehicles…', signout: 'Sign out', expenses: 'Expenses', catalog: 'Products & Services', audit: 'Audit Log', trash: 'Trash', leads: 'Leads & Pipeline', site_visits: 'Site Visits', work_orders: 'Work Orders', tasks: 'Tasks', approvals: 'Approvals', brief: 'Daily Brief', site_reports: 'Daily Site Reports' },
  ar: { inbox: 'صندوق المستندات الذكي', overview: 'لوحة التحكم', documents: 'مستندات الشركة', employees: 'الموظفون والعمالة', vault: 'خزنة المستندات', cheques: 'البنوك والشيكات', invoices: 'الفواتير والمدفوعات', projects: 'المشاريع', parties: 'العملاء والموردون', assets: 'المركبات والأصول', reminders: 'التذكيرات الذكية', calendar: 'التقويم', reports: 'التقارير والتحليلات', assistant: 'Averiqo AI', users: 'إدارة المستخدمين', settings: 'الإعدادات', search: 'ابحث في المستندات والأشخاص والشيكات…', signout: 'تسجيل الخروج', expenses: 'المصروفات', catalog: 'المنتجات والخدمات', audit: 'سجل التدقيق', trash: 'سلة المحذوفات', leads: 'العملاء المحتملون', site_visits: 'زيارات الموقع', work_orders: 'أوامر العمل', tasks: 'المهام', approvals: 'الموافقات', brief: 'الملخص اليومي', site_reports: 'تقارير الموقع اليومية' },
  bn: { inbox: 'স্মার্ট ইনবক্স', overview: 'ড্যাশবোর্ড', documents: 'কোম্পানির নথি', employees: 'কর্মী ও শ্রমিক', vault: 'ডকুমেন্ট ভল্ট', cheques: 'ব্যাংক ও চেক', invoices: 'ইনভয়েস ও পেমেন্ট', projects: 'প্রজেক্ট', parties: 'ক্লায়েন্ট ও সরবরাহকারী', assets: 'যানবাহন ও সম্পদ', reminders: 'স্মার্ট রিমাইন্ডার', calendar: 'ক্যালেন্ডার', reports: 'রিপোর্ট ও বিশ্লেষণ', assistant: 'Averiqo AI', users: 'ইউজার ম্যানেজমেন্ট', settings: 'সেটিংস', search: 'নথি, ব্যক্তি, চেক খুঁজুন…', signout: 'সাইন আউট', expenses: 'খরচ', catalog: 'পণ্য ও সেবা', audit: 'অডিট লগ', trash: 'ট্র্যাশ', leads: 'লিড ও পাইপলাইন', site_visits: 'সাইট ভিজিট', work_orders: 'ওয়ার্ক অর্ডার', tasks: 'কাজ', approvals: 'অনুমোদন', brief: 'দৈনিক সারাংশ', site_reports: 'দৈনিক সাইট রিপোর্ট' },
}
export const t = (l: string, k: Key) => dict[(LOCALES as readonly string[]).includes(l) ? (l as Locale) : 'en'][k]
